/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Kasir;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andri
 */
public class Pecel extends javax.swing.JFrame {

    char type;
    DefaultTableModel tableModel;
    String menu;
    long hargaSatuan = 0, jumlah = 0, totalBayar = 0, total = 0;
    DecimalFormat df = new DecimalFormat("#,###");
    
    
    public Pecel() {
        initComponents();
        long noTransaksi = System.currentTimeMillis();
        notrans.setText(String.valueOf(noTransaksi));
        tableModel = (DefaultTableModel) tblpesanan.getModel();
        tableModel .setRowCount(0);
        txtJumlah.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listmenu = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblpesanan = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        ttlbayar = new javax.swing.JLabel();
        notrans = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Program Kasir Pecel Lamongan");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Program Kasir");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("(Pecel Lamongan)");

        jLabel4.setText("No Transaksi");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Menu"));

        listmenu.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Pecel Telor", "Pecel Ayam", "Pecel Bebek", "Pecel Lele", "Soto Babat", "Soto Ayam", "Usus", "Ati Ampela", "Tahu", "Tempe", "Tempe", "Es Jeruk", "Teh Manis" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listmenu);

        jLabel5.setText("Jumlah");

        txtJumlah.setText("jTextField1");
        txtJumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtJumlahKeyTyped(evt);
            }
        });

        jButton1.setText("Tambahkan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtJumlah, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesanan"));

        tblpesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Menu", "Harga Satuan", "Jumlah Pesan", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Long.class, java.lang.Long.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblpesanan);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(299, 299, 299))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Total Bayar");

        ttlbayar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ttlbayar.setText("0");

        notrans.setText("jLabel7");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(40, 40, 40)
                            .addComponent(notrans))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(121, 121, 121)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)))
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(36, 36, 36)
                        .addComponent(ttlbayar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(notrans))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ttlbayar))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtJumlahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumlahKeyTyped
        type = evt.getKeyChar();
        if (txtJumlah.getText().length() > 1 || !Character.isDigit(type)){
            evt.consume();
        }
    }//GEN-LAST:event_txtJumlahKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (listmenu.isSelectionEmpty()){
            JOptionPane.showMessageDialog(null,"Pesanan Belum Dipilih, silahkan pilih pesanan terlebih dahulu", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
        
        if (txtJumlah.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Jumlah Pesanan Belum Diisi, silahkan isi terlebih dahulu", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
        int mn = listmenu.getSelectedIndex();
        if (!txtJumlah.getText().isEmpty() && !listmenu.isSelectionEmpty()){
            if (listmenu.getSelectedValue().toString().equals("Pecel Telor")){
                menu = listmenu.getSelectedValue().toString();
                hargaSatuan = 8000;
                jumlah = Long.parseLong(txtJumlah.getText());
                total = hargaSatuan*jumlah;
                
                Object[] data = {menu, hargaSatuan,jumlah,total};
                tableModel.addRow(data);
            } else if (listmenu.getSelectedValue().toString().equals("Pecel Ayam")){
                menu = listmenu.getSelectedValue().toString();
                hargaSatuan = 13000;
                jumlah = Long.parseLong(txtJumlah.getText());
                total = hargaSatuan*jumlah;
                
                Object[] data = {menu, hargaSatuan,jumlah,total};
                tableModel.addRow(data);
            } else if (listmenu.getSelectedValue().toString().equals("Pecel Bebek")){
                menu = listmenu.getSelectedValue().toString();
                hargaSatuan = 20000;
                jumlah = Long.parseLong(txtJumlah.getText());
                total = hargaSatuan*jumlah;
                
                Object[] data = {menu, hargaSatuan,jumlah,total};
                tableModel.addRow(data);
            } else if (listmenu.getSelectedValue().toString().equals("Pecel Lele")){
                menu = listmenu.getSelectedValue().toString();
                hargaSatuan = 10000;
                jumlah = Long.parseLong(txtJumlah.getText());
                total = hargaSatuan*jumlah;
                
                Object[] data = {menu, hargaSatuan,jumlah,total};
                tableModel.addRow(data);
            } else if (listmenu.getSelectedValue().toString().equals("Soto Babat")){
                menu = listmenu.getSelectedValue().toString();
                hargaSatuan = 18000;
                jumlah = Long.parseLong(txtJumlah.getText());
                total = hargaSatuan*jumlah;
                
                Object[] data = {menu, hargaSatuan,jumlah,total};
                tableModel.addRow(data);
            } else if (listmenu.getSelectedValue().toString().equals("Soto Ayam")){
                menu = listmenu.getSelectedValue().toString();
                hargaSatuan = 16000;
                jumlah = Long.parseLong(txtJumlah.getText());
                total = hargaSatuan*jumlah;
                
                Object[] data = {menu, hargaSatuan,jumlah,total};
                tableModel.addRow(data);
            } else if (listmenu.getSelectedValue().toString().equals("Usus")){
                menu = listmenu.getSelectedValue().toString();
                hargaSatuan = 3000;
                jumlah = Long.parseLong(txtJumlah.getText());
                total = hargaSatuan*jumlah;
                
                Object[] data = {menu, hargaSatuan,jumlah,total};
                tableModel.addRow(data);
            }  else if (listmenu.getSelectedValue().toString().equals("Tahu")){
                menu = listmenu.getSelectedValue().toString();
                hargaSatuan = 1000;
                jumlah = Long.parseLong(txtJumlah.getText());
                total = hargaSatuan*jumlah;
                
                Object[] data = {menu, hargaSatuan,jumlah,total};
                tableModel.addRow(data);
            } else if (listmenu.getSelectedValue().toString().equals("Tempe")){
                menu = listmenu.getSelectedValue().toString();
                hargaSatuan = 1000;
                jumlah = Long.parseLong(txtJumlah.getText());
                total = hargaSatuan*jumlah;
                
                Object[] data = {menu, hargaSatuan,jumlah,total};
                tableModel.addRow(data);
            } else if (listmenu.getSelectedValue().toString().equals("Es Jeruk")){
                menu = listmenu.getSelectedValue().toString();
                hargaSatuan = 5000;
                jumlah = Long.parseLong(txtJumlah.getText());
                total = hargaSatuan*jumlah;
                
                Object[] data = {menu, hargaSatuan,jumlah,total};
                tableModel.addRow(data);
            } else if (listmenu.getSelectedValue().toString().equals("Teh Manis")){
                menu = listmenu.getSelectedValue().toString();
                hargaSatuan = 3500;
                jumlah = Long.parseLong(txtJumlah.getText());
                total = hargaSatuan*jumlah;
                
                Object[] data = {menu, hargaSatuan,jumlah,total};
                tableModel.addRow(data);
            }
        }
        
        
        long tempTotalbayar = 0;
        for (int i =0; i<tableModel.getRowCount();i++){
            tempTotalbayar = tempTotalbayar + Long.parseLong(tableModel.getValueAt(i,3).toString());
            totalBayar = tempTotalbayar;
        }
        
        ttlbayar.setText("Rp. "+df.format(totalBayar)+",-");
        txtJumlah.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pecel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pecel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pecel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pecel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pecel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listmenu;
    private javax.swing.JLabel notrans;
    private javax.swing.JTable tblpesanan;
    private javax.swing.JLabel ttlbayar;
    private javax.swing.JTextField txtJumlah;
    // End of variables declaration//GEN-END:variables
}
